"""empty message

Revision ID: 837fcb21be25
Revises: cba5c4e43dc2
Create Date: 2019-09-09 10:41:20.360028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837fcb21be25'
down_revision = 'cba5c4e43dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    # ### end Alembic commands ###
